### ISSUE TITLE
Blood Magic Rituals resetting on world reload

### ISSUE THREAD

**Issue by Invadermonky** [asanetargoss/HardcoreAlchemy#10]
### Information:
- Pack Version: 0.8.2

### Description:
Blood Magic Master Ritual Stone NBT data is being pruned with world reloads. Data lost includes:
- Ritual Information
- Activation Status
- Demonic Will Type
- Effect Area Settings
- Chest Location

### Steps to Reproduce:
1. Build a Blood Magic ritual.
2. Activate the ritual.
3. Exit the world.
4. Enter the world.

**Comment by asanetargoss** [comment]
Thanks for the bug report. This release should fix the bug: https://github.com/asanetargoss/HardcoreAlchemy/releases
