### ISSUE TITLE
Blood Magic Rituals (multi)

### ISSUE THREAD

**Issue by Invadermonky** [asanetargoss/HardcoreAlchemy#14]
## Crash
Animus' Ritual of Vengeful Spirits is broken and does not do anything. Additionally, if the ritual is activated without a chest next to the Master Ritual Stone, the game will crash and the save will have to be restored from a backup.

This ritual can be disabled in the Animus config.

## Integrations
I made a mod that integrates the crop mods in the pack into Blood Magic's Reap of the Harvest Moon ritual as well as backporting all of the 1.12.2 Blood Magic rituals to 1.10.2.

https://www.curseforge.com/minecraft/mc-mods/blood-magic-plus

**Comment by asanetargoss** [comment]
That ritual does indeed look rather pointless and I am able to reproduce the crash. It will be disabled in the next modpack update.

I will look at the feature backport addon later.

**Comment by asanetargoss** [comment]
I've added Blood Magic Plus to my test instance. Unless I encounter a major issue, it should be in the next modpack release.
